channels:
  - conda-forge
  - bioconda
  - r
  - jkroes
dependencies:
  - cython
  - python=3.6
  - numpy
  - pandas
  - pip:
      - matplotlib
      - setuptools
      - numpy
      - Keras
      - albumentations
      - tensorflow
      - opencv_python
      - scikit_image
      - jupyter
      - asyncio
      - GitPython
      - pycocotools